---
deployment:
  tasks:
    - export DEPLOYPATH=/home/esnovabe/public_html
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/ 2>/dev/null || :
    - /bin/cp -R js $DEPLOYPATH/ 2>/dev/null || :
    - /bin/cp -R assets $DEPLOYPATH/ 2>/dev/null || :
    - /bin/cp -R images $DEPLOYPATH/ 2>/dev/null || :
