name: 🚀 EsnovaBeton Auto Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Frontend to cPanel public_html
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 5.180.185.253
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/docs/**
            **/*.md
            **/*.json
            **/*.csv
            **/*.py
